---
version: "3"

networks:
  net1:
    enable_ipv6: false
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.10.0/24
        gateway: 192.168.10.1
  net2:
    enable_ipv6: false
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.20.0/24
        gateway: 192.168.20.1
  net100:
    enable_ipv6: false
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.100.0/24
        gateway: 192.168.100.1
  net200:
    enable_ipv6: false
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.200.0/24
        gateway: 192.168.200.1
services:
  R1:
    cap_add:
      - CAP_NET_RAW
      - NET_ADMIN
      - SYS_ADMIN
    privileged: false
    image: frr:2.0
    container_name: R1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
            - $PWD/topology_1a/topology1a/R1:/etc/frr:rw
    command: "/bin/bash /etc/frr/start_frr.sh"
    networks:
      net1:
        ipv4_address: 192.168.10.100
      net100:
        ipv4_address: 192.168.100.100
  R2:
    cap_add:
      - CAP_NET_RAW
      - NET_ADMIN
      - SYS_ADMIN
    privileged: false
    image: frr:2.0
    container_name: R2
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
            - $PWD/topology_1a/topology1a/R2:/etc/frr:rw
    command: "/bin/bash /etc/frr/start_frr.sh"
    networks:
      net100:
        ipv4_address: 192.168.100.200
      net200:
        ipv4_address: 192.168.200.200

  R3:
    cap_add:
      - CAP_NET_RAW
      - NET_ADMIN
      - SYS_ADMIN
    privileged: false
    image: frr:2.0
    container_name: R3
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
            - $PWD/topology_1a/topology1a/R3:/etc/frr:rw
    command: "/bin/bash /etc/frr/start_frr.sh"
    networks:
      net2:
        ipv4_address: 192.168.20.210
      net200:
        ipv4_address: 192.168.200.210

  HostA:
    cap_add:
      - CAP_NET_RAW
      - NET_ADMIN
      - SYS_ADMIN
    privileged: false
    image: frr:2.0
    container_name: HostA
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
            - $PWD/topology_1a/topology1a/HostA:/etc/frr:rw
    command: "/bin/bash /etc/frr/start_frr.sh"
    networks:
      net1:
        ipv4_address: 192.168.10.99
        
  HostB:
    cap_add:
      - CAP_NET_RAW
      - NET_ADMIN
      - SYS_ADMIN
    privileged: false
    image: frr:2.0
    container_name: HostB
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
            - $PWD/topology_1a/topology1a/HostB:/etc/frr:rw
    command: "/bin/bash /etc/frr/start_frr.sh"
    networks:
      net2:
        ipv4_address: 192.168.20.99
